export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CREATE_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_SHOP = "FETCH_SHOP";
export const CREATE_SHOP = "CREATE_SHOP";
export const CREATE_USER = "CREATE_USER";
